language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
   directories:
     - $HOME/.composer/cache/files

script:
    - ant -f build/build.xml -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-continuous static-lint

notifications:
    email: false
    irc: "chat.freenode.net#shopware-dev"

matrix:
  allow_failures:
    - php: hhvm
